name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install torch  # Instala PyTorch
          pip install pytest  # Instala pytest

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Node.js dependencies
        run: npm install

      - name: Start Flask server
        run: |
          nohup python app.py &
        env:
          FLASK_ENV: development

      - name: Wait for Flask server to be ready
        run: sleep 20  # Aumenta o tempo de espera para garantir que o servidor Flask esteja pronto

      - name: Run Cypress tests
        run: npx cypress run

      - name: Run Python tests
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          pytest tests  # Especifica o diretório de testes
