name: Run Tests

on:
  push:
    branches:
      - main  # Ou a branch que você deseja executar o fluxo de trabalho
  pull_request:
    branches:
      - main  # Ou a branch que você deseja executar o fluxo de trabalho

jobs:
  test:
    runs-on: ubuntu-latest  # Ou o sistema operacional que você está utilizando

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Versão do Python que você está utilizando

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest tests/test_benchmark.py  # Executa o teste benchmark
        pytest tests/test_benchmark_quality.py  # Executa o teste benchmark_quality
